### PR TITLE
Adding maryam #518

### PR DESCRIPTION
**Pull request by esskayesss**
Adding python-maryam as a git package as per issue #518 
It has been tested. It builds and runs fine.

### CODE REVIEW

**Comment by esskayesss** [comment]
I have a questions from the members. Is there a page with a well documented list of archstrike groups? What rules decide which package goes under what set of groups?

**Comment by Cthulu201** [comment]
Thanks for the question. The following command will show you the AS groups:

pacman -Sg | grep archstrike

https://archstrike.org/wiki

**Comment by esskayesss** [comment]
> Thanks for the question. The following command will show you the AS groups:
> 
> pacman -Sg | grep archstrike
> 
> https://archstrike.org/wiki

I'm aware of that... That's what I've been using as reference as of now... I'd assume it doesn't get clearer than that then...

**Comment by Cthulu201** [comment]
Correct. By the way, thanks for the PR contributions, going through another right now.

**Comment by esskayesss** [comment]
I'm glad I can be of help! I'll make a lot more next month. I'm busy with some examinations at the moment.

**Comment by Cthulu201** [comment]
Completely understand, we're feeling that pinch at the moment.

**Comment by xorond** [comment]
hey, i've merged this with a follow-up commit to fix the dependencies, otherwise it wouldn't build in my clean chroot. thanks for contributing!

**Pull request merged**
